### ISSUE TITLE
Service `/ws/collection/{collectionID}/contact.json` returns 500 error

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/collectory#54]
This is causing ozcam to error on [occurrence record pages](https://ozcam.ala.org.au/occurrences/b259959b-67df-40e9-9dbd-d06075d4560e). 

https://collections.ala.org.au/ws/collection/co10/contact.json

```
java.lang.NullPointerException: Cannot invoke method getContacts() on null object
	at au.org.ala.collectory.DataController$_closure37.doCall(DataController.groovy:811)
	at org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker.invoke(DefaultGrailsControllerClass.java:223)
	at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
	at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
```

**Comment by nickdos** [comment]
Code checked ✅

**Comment by nickdos** [comment]
https://collections-test.ala.org.au/ws/collection/co13/contacts/20.json still showing an error with `3.0.2-SNAPSHOT`

**Comment by Rita-C** [comment]
Both links above still showing `500` error, has the update been deployed @nickdos ?

**Comment by nickdos** [comment]
Fixed on test (take 2)

**Comment by Rita-C** [comment]
`uri` in https://collections-test.ala.org.au/ws/collection/co40/contacts/184.json is `"https://collections-test.ala.org.au/ws/collection/co117/contacts/196"`, is this correct?

and If I made up an ID, e.g. https://collections-test.ala.org.au/ws/collection/co13/contacts/200012312.json, it returns a result, don't feel it's right.

**Comment by nickdos** [comment]
The uri is not quite right but same as it is on prod... it should return JSON but is defaulting to CSV for some reason. I'll add a fix for this.

The made-up user is showing the "expected" result, which is to show all users for a collection, the same as https://collections-test.ala.org.au/ws/collection/co13/contacts.json.

**Comment by Rita-C** [comment]
LGTM
