### ISSUE TITLE
Editing a `co` page throws an error on test site

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/collectory#59]
Doing smoke testing for release. https://collections-test.ala.org.au/collection/edit/co40?page=description - adding some text to the "Public Description" field and then clicking "Update" results in an error page. Performing same steps on prod works as expected. 

This needs fixing before version 3.0.2 can be deployed. 

```
Error 500: Cannot cast object 'preserved' with class 'java.lang.String' to class 'grails.converters.JSON'
Servlet: grailsDispatcherServlet
URI: /collection/base
Exception Message: Cannot cast object 'preserved' with class 'java.lang.String' to class 'grails.converters.JSON'
Caused by: Cannot cast object 'preserved' with class 'java.lang.String' to class 'grails.converters.JSON'
Class: UrlMappingsInfoHandlerAdapter
At Line: [90] 
```

Stack trace:
```
org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'preserved' with class 'java.lang.String' to class 'grails.converters.JSON'
	at au.org.ala.collectory.CollectionController.entitySpecificDescriptionProcessing(CollectionController.groovy:205)
	at au.org.ala.collectory.ProviderGroupService.$tt__entitySpecificDescriptionProcessing(ProviderGroupService.groovy:170)
	at grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)
	at au.org.ala.collectory.ProviderGroupService.$tt__updateDescription(ProviderGroupService.groovy:151)
	at grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)
	at au.org.ala.collectory.ProviderGroupController$_closure12.doCall(ProviderGroupController.groovy:257)
	at org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker.invoke(DefaultGrailsControllerClass.java:223)
	at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
	at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
	at org.jasig.cas.client.util.HttpServletRequestWrapperFilter.doFilter(HttpServletRequestWrapperFilter.java:71)
	at org.jasig.cas.client.validation.AbstractTicketValidationFilter.doFilter(AbstractTicketValidationFilter.java:236)
	at org.jasig.cas.client.session.SingleSignOutFilter.doFilter(SingleSignOutFilter.java:97)
	at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
	at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:128)
	at org.springframework.boot.web.servlet.support.ErrorPageFilter.access$000(ErrorPageFilter.java:66)
	at org.springframework.boot.web.servlet.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:103)
	at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:121)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)\n
```

**Comment by nickdos** [comment]
Works now.
