### ISSUE TITLE
`providerMap` list page errors when `max` param specified

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/collectory#86]
https://collections.ala.org.au/providerMap/list gives expected results. However, manually specifying a custom `max` param throws `500` error: https://collections.ala.org.au/providerMap/list?max=200&order=asc.

> Error 500: No signature of method: grails.orm.HibernateCriteriaBuilder.maxResults() is applicable for argument types: (String) values: [200]
 ```groovy.lang.MissingMethodException: No signature of method: grails.orm.HibernateCriteriaBuilder.maxResults() is applicable for argument types: (String) values: [200]
	at org.grails.orm.hibernate.query.AbstractHibernateCriteriaBuilder.invokeMethod(AbstractHibernateCriteriaBuilder.java:1847)
	at au.org.ala.collectory.ProviderMapController$_closure2$_closure9.doCall(ProviderMapController.groovy:32)
```

**Comment by nickdos** [comment]
@Rita-C  please code review [83c368c](https://github.com/AtlasOfLivingAustralia/collectory/commit/83c368cffcb62bfb4ececa090a576f63fb473550), when you have a chance.
